#!/usr/bin/env bash

read -rp 'This script will install Arch Linux. Do you want to continue? (y/n): ' yn
if [[ ! $yn =~ ^[Yy]$ ]]; then
    exit
fi

clear

read -rp "Please enter your timezone (e.g., Europe/London): " timezone
read -rp "Please enter your keyboard layout (get from the Arch Linux wiki if needed): " layout
read -rp "Please enter your username for the installation: " username
read -rp "Please enter your hostname for the installation: " hostname

# Validate timezone and keyboard layout
timedatectl set-timezone "$timezone" && echo "Timezone set to $timezone"
timedatectl set-ntp true
loadkeys "$layout"

clear

cfdisk /dev/sda

mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2
mkswap /dev/sda3
swapon /dev/sda3

mount /dev/sda1 /mnt
mkdir /mnt/home
mount /dev/sda2 /mnt/home

read -rp "Would you like to set up the fastest mirrors? (y/n): " mirror_yn
if [[ $mirror_yn =~ ^[Yy]$ ]]; then
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    pacman -Syy pacman-contrib
    rankmirrors -n 10 /etc/pacman.d/mirrorlist.bak > /etc/pacman.d/mirrorlist
fi

read -rp "Would you like to install vim and neofetch with your base installation? (y/n): " tools_yn
if [[ $tools_yn =~ ^[Yy]$ ]]; then
    base_pkgs=("base" "base-devel" "linux" "intel-ucode" "sudo" "nano" "vim" "neofetch" "networkmanager" "dhcpcd" "pipewire")
else
    base_pkgs=("base" "base-devel" "linux" "intel-ucode" "sudo" "nano" "networkmanager" "dhcpcd" "pipewire")
fi

pacstrap -i /mnt "${base_pkgs[@]}"
genfstab -U /mnt > /mnt/etc/fstab

arch-chroot /mnt passwd
arch-chroot /mnt useradd -m "$username"
arch-chroot /mnt passwd "$username"
arch-chroot /mnt usermod -aG wheel,storage,power "$username"
arch-chroot /mnt EDITOR=nano visudo
arch-chroot /mnt nano /etc/locale.gen
arch-chroot /mnt locale-gen

read -rp "Please enter the language code you want to uncomment (e.g., en_GB.UTF-8): " lang_code
echo "LANG=\"$lang_code\"" > /mnt/etc/locale.conf
echo "export LANG=\"$lang_code\"" >> /mnt/etc/profile

arch-chroot /mnt echo "$hostname" > /mnt/etc/hostname
arch-chroot /mnt nano /mnt/etc/hosts
arch-chroot /mnt ln -sf /usr/share/zoneinfo/"$timezone" /mnt/etc/localtime

arch-chroot /mnt mkdir /boot/efi
arch-chroot /mnt mount /dev/sda1 /boot/efi
arch-chroot /mnt pacman -S grub efibootmgr dosfstools mtools
arch-chroot /mnt nano /etc/default/grub
arch-chroot /mnt pacman -S os-prober
arch-chroot /mnt grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

arch-chroot /mnt systemctl enable dhcpcd
arch-chroot /mnt systemctl enable NetworkManager

printf "Rebooting and unmounting. Enjoy your new installation!\n"

arch-chroot /mnt umount -R /mnt
reboot