#! /bin/sh

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

if [ "$instance" = termite ] ; then
	case "$title" in
		zfetch)
		    echo "border=off state=floating rectangle=616x354+36+115"
		    ;;
		sysfetch)
		    echo "border=off state=floating rectangle=352x500+36+115"
		    ;;
		updating)
			echo "state=floating rectangle=483x190+1090+72"
			;;
		floaterm)
			echo "state=floating center=on rectangle=781x451+0+0"
	esac
fi

main () {
case "$class" in
	mpv)
	    eval "$consequences"
		[ "$state" ] || echo "state=floating focus=on center=on rectangle=925x519+0+0 border=off"
		;;
	whatsapp-nativefier-d40211 | snapchat-nativefier-c2906f)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^4 border=off center=on follow=on rectangle=930x617+0+0"
		;;
	netflix-nativefier-b2d713)
		eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^5 center=on follow=on rectangle=1480x820+0+0"
		;;
	retroarch)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^6 center=on follow=on border=off"
	    ;;
	Pavucontrol)
	    eval "$consequences"
	    [ "$state" ] || echo "state=floating follow=on center=on rectangle=930x617+0+0 border=off"
	    ;;
	Thunar)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on center=on border=off"
	    ;;
	firefox)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^1 border=off rectangle=1480x820+0+0 center=on follow=on"
	    ;;
	discord)
		eval "$consequences"
		[ "$state" ] || echo "state=pseudo_tiled desktop=^3 border=off rectangle=1480x820+0+0 center=on follow=on"
		;;
	Bitwarden)
		eval "$consequences"
		[ "$state" ] || echo "state=pseudo_tiled desktop=^8 border=off rectangle=1480x820+0+0 center=on follow=on"
		;;
	minecraft-launcher)
		eval "$consequences"
		[ "$state" ] || echo "state=pseudo_tiled desktop=^9 border=off rectangle=1480x820+0+0 center=on follow=on"
		;;
	Spotify)
		eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled center=on border=off rectangle=1124x600 desktop=^6 follow=on"
		;;
		"")
        sleep 0.5
		wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))
		class=${wm_class[-1]}
		[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}
		[[ -n "$class" ]] && main
		;;
esac
}

main
case "$instance" in
     Toolkit)
        eval "$consequences"
        [ "$state" ] || echo "state=floating sticky=on rectangle=500x290+1054+593"
	    ;;
esac  
